### PR TITLE
Fixed SetPaths kafka script generation issue.

### PR DESCRIPTION
**Pull request by ligadata-william**
Fixed SetPaths kafka script generation incompatibility with kafka version 0.9+. Also fixed an issue where easy install failed to copy a migrateTo jar when install 2.10.

### CODE REVIEW

**Comment by ligadata-william** [comment]
@ligadata-tulasi can you review my changes?

**Comment by ligadatahari** [comment]
This has conflicts, needs to be rebased

**Comment by ligadata-william** [comment]
@ligadatahari I've resolved the merge conflict. It should be ready to review.

**Comment by ligadatahari** [comment]
looks good

**Pull request merged**
