### PR TITLE
Udf unit tests

### PR DESCRIPTION
**Pull request by ligadata-william**
This contains roughly 90 unit tests for UDFs. I've also marked certain packages to be exempt from code coverage that do not directly impact kamanja or are not used very often.

### CODE REVIEW

**Comment by ligadata-william** [comment]
@ligadata-pokuri Have you had time to review this? Is it ok to merge?

**Comment by ligadata-pokuri** [comment]
I will check couple of your pull requests today evening

**Comment by ligadata-pokuri** [comment]
William you can merge this in 1.4.0.Base branch

**Comment by ligadata-william** [comment]
Refer to #1002 instead.

**Pull request closed without merging**
