### PR TITLE
Rest for pmml

### PR DESCRIPTION
**Pull request by ligadata-dan**
@ligadata-william 

Here are my results:

danielkozin$ curl -X POST -k  https://localhost:8081/api/model/pmml -d @'/Users/danielkozin/kamanjaApps/JpmmlExample/DecisionTreeEnsembleIris.pmml' --header "modelconfig:system.Model1,1.0.0,system.irismsg"
{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:system.model1.000001000000000000"
  }
}

**INVALID HEADER (MISSING 3 required fields for PMML)**
danielkozin$ curl -X POST -k  https://localhost:8081/api/model/pmml -d @'/Users/danielkozin/kamanjaApps/JpmmlExample/DecisionTreeEnsembleIris.pmml' --header "modelconfig:system.Model1,1.0.0"
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModelService",
    "Result Data" : null,
    "Result Description" : "Error: Invalid compile config paramters specified for PMML, Needs ModelName, ModelVersion, MessageName."
  }
}

**if no HEADER is passed it, the code will assume KPMML implementation, and I see**

 danielkozin$ curl -X POST -k  https://localhost:8081/api/model/pmml -d @'/Users/danielkozin/kamanjaApps/JpmmlExample/DecisionTreeEnsembleIris.pmml'
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Error :com.ligadata.Exceptions.ModelCompilationFailedException: key not found: ClassNameFailed to Add Model"
  }
}

### CODE REVIEW

**Comment by ligadata-ahmad** [comment]
I am getting compilation error 

[error] /data/Ahmed/Test/Kamanja-restForPMML/trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/AddModelService.scala:72: not found: value looger
[error]         looger.info ("No configuration information provided, assuming Kamanja PMML implementation.")
[error]         ^
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[info] Compiling 2 Scala sources and 4 Java sources to /data/Ahmed/Test/Kamanja-restForPMML/trunk/SampleApplication/InterfacesSamples/target/scala-2.11/classes...
[info] Compiling 4 Scala sources to /data/Ahmed/Test/Kamanja-restForPMML/trunk/FileDataConsumer/target/scala-2.11/classes...
[error] /data/Ahmed/Test/Kamanja-restForPMML/trunk/MetadataAPIService/src/main/scala/com/ligadata/metadataapiservice/UpdateModelService.scala:64: not found: value looger
[error]         looger.info ("No configuration information provided, assuming Kamanja PMML implementation.")
[error]         ^
[error] two errors found

**Comment by ligadata-krishna** [comment]
How can someone get compilation error in checked in code? Code should be compiled at minimum before check-in into the system.

 

Thanks

-Krishna

**Comment by ligadata-dan** [comment]
Krishna,

This was my mistake… I finished testing the code, and pushed the changes, then I just added a quick Logger statement (which I thought could be useful)  which had an spelling error in it.

I was trying to do several things at once and just missed it.  Its an oversight on my part,

**Comment by ligadata-ahmad** [comment]
I am attaching the result for testing The RestAPI .
[TestRESTAPI.txt](https://github.com/ligaDATA/Kamanja/files/114809/TestRESTAPI.txt)

All the commands that I have tested work fine except  adding **scala model** with the following  error  . The issue is that the generated scala code(attached) is not well formatted. 
[HelloWorldModel.scala.txt](https://github.com/ligaDATA/Kamanja/files/114818/HelloWorldModel.scala.txt)


 

> /data/Ahmed/Test/kamanja/workingdir/HelloWorldModel/HelloWorldModel.scala:1: error: '{' expected but identifier found.
> package com.ligadata.samples.modelsimport com.ligadata.KamanjaBase._import com.ligadata.KvBase.TimeRangeimport com.ligadata.kamanja.metadata.ModelDef.V0;
>                                           ^
> /data/Ahmed/Test/kamanja/workingdir/HelloWorldModel/HelloWorldModel.scala:4: error: ';' expected but identifier found.
> import com.ligadata.KamanjaBase._import com.ligadata.KvBase.TimeRangeimport com.ligadata.kamanja.metadata.ModelDef.V0;
>                                         ^
> /data/Ahmed/Test/kamanja/workingdir/HelloWorldModel/HelloWorldModel.scala:5: error: ';' expected but identifier found.
> import com.ligadata.KamanjaBase._import com.ligadata.KvBase.TimeRangeimport com.ligadata.kamanja.metadata.ModelDef;class HelloWorldModelFactory(modelDef: ModelDef, nodeContext: NodeContext) extends ModelInstanceFactory(modelDef, nodeContext) {  override def isValidMessage(msg: MessageContainerBase): Boolean = return msg.isInstanceOf[msg1]  override def createModelInstance(): ModelInstance = return new HelloWorldModel(this)  override def getModelName: String = "HelloWorldModel"   override def getVersion: String = "0.0.1"  override def createResultObject(): ModelResultBase = new MappedModelResults()}class HelloWorldModel(factory: ModelInstanceFactory) extends ModelInstance(factory) {     override def execute(txnCtxt: TransactionContext, outputDefault: Boolean):ModelResultBase = {          var helloWorld : msg1 =  txnCtxt.getMessage().asInstanceOf[msg1]             if(helloWorld.score!=1)          return null;          var actualResults: Array[Result] = Array[Result](new Result("Id",helloWorld.id),                                                        new Result("Name",helloWorld.Name),                                                        new Result("Score",helloWorld.score))     return factory.createResultObject().asInstanceOf[MappedModelResults].withResults(actualResults)   }     }
>                                         ^
> /data/Ahmed/Test/kamanja/workingdir/HelloWorldModel/HelloWorldModel.scala:5: error: ';' expected but 'override' found.
> import com.ligadata.KamanjaBase._import com.ligadata.KvBase.TimeRangeimport com.ligadata.kamanja.metadata.ModelDef;class HelloWorldModelFactory(modelDef: ModelDef, nodeContext: NodeContext) extends ModelInstanceFactory(modelDef, nodeContext) {  override def isValidMessage(msg: MessageContainerBase): Boolean = return msg.isInstanceOf[msg1]  override def createModelInstance(): ModelInstance = return new HelloWorldModel(this)  override def getModelName: String = "HelloWorldModel"   override def getVersion: String = "0.0.1"  override def createResultObject(): ModelResultBase = new MappedModelResults()}class HelloWorldModel(factory: ModelInstanceFactory) extends ModelInstance(factory) {     override def execute(txnCtxt: TransactionContext, outputDefault: Boolean):ModelResultBase = {          var helloWorld : msg1 =  txnCtxt.getMessage().asInstanceOf[msg1]             if(helloWorld.score!=1)          return null;          var actualResults: Array[Result] = Array[Result](new Result("Id",helloWorld.id),                                                        new Result("Name",helloWorld.Name),                                                        new Result("Score",helloWorld.score))     return factory.createResultObject().asInstanceOf[MappedModelResults].withResults(actualResults)   }     }
>                                                                                                                                                                                                                                                                                                                                                       ^
> /data/Ahmed/Test/kamanja/workingdir/HelloWorldModel/HelloWorldModel.scala:5: error: ';' expected but 'class' found.

**Comment by ligadata-ahmad** [comment]
@ligadata-dan  you were right the issue for adding scala model came from curl command 

It worked fine for me after adding by  **--data-binary**  to the command .

Command : 

curl -X POST --data-binary "@/data/Ahmed/Test/kamanja/input/SampleApplications/metadata/model/HelloWorld.scala"  -k  https://localhost:8081/api/model/scala  --header "modelconfig:HelloWorldModel"

Result :

{
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.samples.models.helloworldmodel.000000000000000001"
  }
}

**Comment by ligadata-dan** [comment]
@ligadata-ahmad 

Awesome! Sounds good

**Pull request merged**
