### PR TITLE
Redistributing only if the current node is Leader. Otherwise we are s…

### PR DESCRIPTION
**Pull request by ligadata-pokuri**
…imply ignoring redistribution & reset expectedNodesAction

### CODE REVIEW

**Comment by ligadata-william** [comment]
@ligadata-pokuri I am able to reproduce this issue still. NodeID 1 on my environment has a deadlock. I've attached the jstack.
[frozenOnDist.txt](https://github.com/LigaData/Kamanja/files/1032060/frozenOnDist.txt)

**Comment by ligadata-william** [comment]
On the node that hangs, I get these two pieces of logging and then the node stops logging altogether (in WARN mode, not DEBUG).
```
 WARN [Curator-ConnectionStateManager-0] - DistributionCheck:EnvCtxtEventChangeCallback. Entered from EnvCtxtEventChangeCallback. Got new ClusterStatus. NodeId:NodeId-1-UUID-075ec7a6-5881-4ebc-82a5-6f46f63e1c24, LeaderNodeId:NodeId-1-UUID-075ec7a6-5881-4ebc-82a5-6f46f63e1c24, Participents:NodeId-1-UUID-075ec7a6-5881-4ebc-82a5-6f46f63e1c24,NodeId-2-UUID-4daeab7a-35fd-448f-ab07-036c5d938f30,NodeId-3-UUID-85029684-4776-4f0f-9e5a-ca2a9a7aba30, isLeader:false
 WARN [Curator-Framework-0-EventThread] - DistributionCheck:EnvCtxtEventChangeCallback. Entered from EnvCtxtEventChangeCallback. Got new ClusterStatus. NodeId:NodeId-1-UUID-075ec7a6-5881-4ebc-82a5-6f46f63e1c24, LeaderNodeId:NodeId-1-UUID-075ec7a6-5881-4ebc-82a5-6f46f63e1c24, Participents:NodeId-1-UUID-075ec7a6-5881-4ebc-82a5-6f46f63e1c24,NodeId-2-UUID-4daeab7a-35fd-448f-ab07-036c5d938f30,NodeId-3-UUID-85029684-4776-4f0f-9e5a-ca2a9a7aba30, isLeader:false
```

**Comment by ligadata-pokuri** [comment]
@ligadata-william , I added code for deadlock while shutdown & distribution at the same time. Can you test it and let me know

**Comment by ligadata-william** [comment]
@ligadata-pokuri I can't reproduce the deadlock anymore but once zookeeper comes back online, it appears as though messages aren't being processed anymore. Upon attempting to shut down the cluster, Node 1 seems to be hanging and even a kill -9 fails to shut it down. I've attempted to retrieve a JStack for the process but I get the follow error (post kill -9 command):
```
21479: Connection refused
```

**Comment by ligadata-william** [comment]
This has been fixed as part of #1620. Closing.

**Pull request closed without merging**
