### PR TITLE
Help menu updated with correct command dump all cluster config

### PR DESCRIPTION
**Pull request by ligadata-dhaval**
This branch will have 2-3 more code changes related to kamanja command line as well

### CODE REVIEW

**Comment by ligadata-william** [comment]
@ligadata-dhaval I'm a month and a half behind on this one but I have one issue that needs to be resolved before I can merge this:
When I run:
```
kamanja get all models|messages|containers
```
I get the list as expected, however it appears as such:
```
Result:
system.envcontext.000000000000000001
system.dyspnoeacodes.000000000001000000
system.messagecontainerbase.000000000000000001
system.basecontainer.000000000000000001
system.sputumcodes.000000000001000000
system.envcodes.000000000001000000
system.context.000000000000000001
system.coughcodes.000000000001000000
system.basemsg.000000000000000001
system.smokecodes.000000000001000000
```
which is different from the result typically returned. This needs to be returned in the APIResult JSON format that all other operations are returned in.

**Comment by ligadata-dhaval** [comment]
Hi William,

As discussed, I have updated the code for messages to give the below result:

Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "MessageService",
    "Result Data" : "system.inpatientclaim.000000000001000000, system.hl7.000000000001000000, system.beneficiary.000000000001000000, ",
    "Result Description" : "Successfully retrieved all the messages"
  }
}

I will check in the code as soon as I complete models and containers

**Comment by ligadata-dan** [comment]
you have an extra coma at the end of Result Data string

**Comment by ligadata-william** [comment]
Looks like you may need to use mkString on the list a specify the comma as the separator, assuming you're manually creating this. Need to look at the code.

**Comment by ligadata-william** [comment]
Is the metadataAPIImpl def not returning an APIResult when you call get all <object>?

**Comment by ligadata-dhaval** [comment]
It returns an array of string which contains the keys of the container, message or model. I will update the code to avoid that extra comma.

**Comment by ligadata-dhaval** [comment]
Hi, I have updated the code for all. Please find below the structure:
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "MessageService",
    "Result Data" : "system.beneficiary.000000000001000000, system.hl7.000000000001000000, system.outpatientclaim.000000000001000000, system.msg1.000000000001000000, system.inpatientclaim.000000000001000000",
    "Result Description" : "Successfully retrieved all the messages"
  }
}

The last comma is the one for son format now.

**Comment by ligadata-krishna** [comment]
I didn’t realize that all Kamanja commands return results in JSON format. The intention in proposing these commands was to provide them as human friendly and it seems output JSON defeats that purpose. One approach is to take a flag for type of return results and format them accordingly (--h for human readable format, --j for json or something like that).

 

Thanks

-Krishna

**Pull request merged**
