### PR TITLE
1.5.3 phoenix  dcel 27

### PR DESCRIPTION
**Pull request by ligadata-saleh**

### CODE REVIEW

**Comment by ligadata-pokuri** [comment]
@ligadata-william, can you review the code and test this?

**Comment by ligadata-william** [comment]
@ligadata-pokuri while reviewing the code and the merge conflict that exists, I noticed the original code this was based on no longer exists and more sophisticated wait logic exists in it's place (hence the conflict). Is this pull request relevant anymore?

**Comment by ligadata-saleh** [comment]
Hi @ligadata-william & @ligadata-pokuri  , 

    looking at the conflict , it looks like this is already solved , also i can see a bug in my branch am not setting the await time value to anything after subbing the code will exit from the loop  .

Thanks
Saleh

**Comment by ligadata-pokuri** [comment]
Closing this, because we opened another pull request https://github.com/LigaData/Kamanja/pull/1597 on new sources

**Pull request closed without merging**
