### PR TITLE
Fatafat218 "Auto" test cases

### PR DESCRIPTION
**Pull request by ligadata-rich**
The jpmml "auto" test cases have been added to this branch (built on top of Sprint8FeaturesWithJpmml)

The message, the kamanja ingestion commands for auto message and models, and commands for generating
the jpmml evaluator test results, and test data have all been added.

William, I will add a pull request to pull this into the Sprint8FeaturesWithJpmml if you desire (more like if you
have time).

### CODE REVIEW

**Comment by donald-ligadata** [comment]
I want to check, is it possible for anyone outside the company to see this message?

 

Donald

**Comment by ligadata-william** [comment]
Can one of the admins verify this patch?

**Comment by ligadata-william** [comment]
Hey @ligadata-rich I'm not sure how valid this pull request is anymore. Have any of these changes made their way into dev already? If not, do we want to merge it into the 1.4.0.Base branch?

There are a few coded changes. If it's something we need, I'll test and merge as soon as I can.

**Comment by ligadata-rich** [comment]
That was a long time ago.  I suggest we* not merge* this for the time
being.  Maybe this can be restated in a new pull request on the next sprint
after examining exactly what was in there.  I don't really have time to
look at this juncture.

**Comment by ligadata-william** [comment]
I'm closing this for now. We can open a new one later if the need arises.

**Pull request closed without merging**
