### PR TITLE
Kamanja 1035 Alternate command parser and help menu update

### PR DESCRIPTION
**Pull request by ligadata-dhaval**
Remove Alternate command parser usage from Metadata API. AlternateCmdParser.scala commented out. Also, commented the method def AltRoute(origArgs: Array[String]) as it is not being used in the StartMetadataAPI.scala

### CODE REVIEW

**Comment by ligadata-dhaval** [comment]
Renumbered the help menu

**Comment by ligadata-william** [comment]
Tested and didn't find any busted functionality here.  @ligadata-dhaval can you close this pull request and open a new one against 1.5.0?

**Comment by ligadata-dhaval** [comment]
Closing as it needs to be against 1.5.0. Creating a new one.

**Comment by ligadata-dhaval** [comment]
New pull request no  #1188

**Pull request closed without merging**
