### PR TITLE
End point tools status into kafka

### PR DESCRIPTION
**Pull request by ligadata-pokuri**
Kamanja Endpoint services for Kafka-HDFS/SQL's statistics logging into kafka

### CODE REVIEW

**Comment by ligadata-dhaval** [comment]
HDFS: (Below cases for both only one key in the batch & multiple keys in the batch)
	1. All Keys Succeeded
		Pass a single record in a batch and verify the output, successful, failed and exceptions.
		Pass multiple records of the same date and verify the batch record count and the result.
		Pass multiple records of different dates (3-5 records of same date) and verify the batch.
	2. Some keys failed
		Pass records with a few of them having error and verify the results.
	3. All Keys failed
		Pass records where all keys fail and verify the error msgs which should be as per the limit set.
	4. Failed Kafka buffer exceeded
		-
	5. Failed Kafka buffer in control
		-

**Comment by ligadata-dhaval** [comment]
[hdfs.txt](https://github.com/LigaData/Kamanja/files/559310/hdfs.txt)

**Comment by ligadata-ahmad** [comment]
The following test cases are verified for sql adapter : 
1. ALL Successful 
2. Partiality Failed 
3. All failed

here is the output for each test case 
[testcases.txt](https://github.com/LigaData/Kamanja/files/559542/testcases.txt)

**Comment by ligadata-ahmad** [comment]
the following is another two test cases :
* Failed Kafka buffer exceeded 
[Failed Kafka buffer exceeded.txt](https://github.com/LigaData/Kamanja/files/559598/Failed.Kafka.buffer.exceeded.txt)

*  Failed Kafka buffer in control 
[Failed_Kafka_buffer_in_control.txt](https://github.com/LigaData/Kamanja/files/559599/Failed_Kafka_buffer_in_control.txt)

**Pull request merged**
