### PR TITLE
Encrypt password utils

### PR DESCRIPTION
**Pull request by ligadata-ramana**
[HowToUsePasswordEncryptionUtils.txt](https://github.com/LigaData/Kamanja/files/567955/HowToUsePasswordEncryptionUtils.txt)

1. Do a kamanja  build in this branch
2. Do a mvn package in Utils/OutputUtils
    (you need to install libraries SaveContainerDataComponent and KamanjaInternalDeps manually
     at least once before executing mvn package)
3. Refer to attached document for more details on usage.

### CODE REVIEW

**Comment by ligadata-william** [comment]
@ligadata-ramana I'm getting some compiler errors when I run easyInstallKamanja.sh I have JDK 1.7 installed.

```
[error] /Users/william/dev/Kamanja/trunk/Utils/EncryptUtils/src/main/java/com/ligadata/EncryptUtils/EncryptionUtil.java:34: error: cannot find symbol
[error] import java.util.Base64;
[error]                 ^
[error]   symbol:   class Base64
[error]   location: package java.util
[error] /Users/william/dev/Kamanja/trunk/Utils/EncryptUtils/src/main/java/com/ligadata/EncryptUtils/EncryptionUtil.java:34: error: cannot find symbol
[error] import java.util.Base64;
[error]                 ^
[error]   symbol:   class Base64
[error]   location: package java.util
[error] /Users/william/dev/Kamanja/trunk/Utils/EncryptUtils/src/main/java/com/ligadata/EncryptUtils/EncryptionUtil.java:216: error: cannot find symbol
[error] 	    String encoded = Base64.getEncoder().encodeToString(bytes);
[error] 	                     ^
[error]   symbol:   variable Base64
[error]   location: class EncryptionUtil
[error] /Users/william/dev/Kamanja/trunk/Utils/EncryptUtils/src/main/java/com/ligadata/EncryptUtils/EncryptionUtil.java:235: error: cannot find symbol
[error] 	    byte[] decoded = Base64.getDecoder().decode(s.getBytes());
[error] 	                     ^
[error]   symbol:   variable Base64
[error]   location: class EncryptionUtil
[error] /Users/william/dev/Kamanja/trunk/Utils/EncryptUtils/src/main/java/com/ligadata/EncryptUtils/EncryptionUtil.java:254: error: cannot find symbol
[error] 	    String decoded = new String(Base64.getDecoder().decode(bytes));
[error] 	                                ^
[error]   symbol:   variable Base64
[error]   location: class EncryptionUtil
[error] 4 errors
```

**Comment by ligadata-ramana** [comment]
I used apache-commons-codec  library to handle the base64 encoding and decoding. I have also separated the dependency of encrypt utils on Kamanja librraies. Now encrypt/decrypt utils depend on KamanjaEndpointServices.jar only. I have updated my notes as well (attached)

**Comment by ligadata-ramana** [comment]
[HowToUsePasswordEncryptionUtils.txt](https://github.com/LigaData/Kamanja/files/572604/HowToUsePasswordEncryptionUtils.txt)

**Comment by ligadata-william** [comment]
@ligadata-ramana I'm running into an error with mvn package for the OutputUtils project. It appears to be having issues locating a jdbc jar. I have a copy on my laptop but I'm not sure where I should place it for maven to work.

```
[ERROR] Failed to execute goal on project KafkaOutputAdapters: Could not resolve dependencies for project com.ligadata:KafkaOutputAdapters:jar:1.0: The following artifacts could not be resolved: com.microsoft.sqlserver:sqljdbc4:jar:4.2, com.ligadata.kamanja:SaveContainerDataComponent:jar:1.5.3, com.ligadata.kamanja:KamanjaInternalDeps:jar:1.5.3: Could not find artifact com.microsoft.sqlserver:sqljdbc4:jar:4.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by ligadata-william** [comment]
I've run the following command
```
mvn install:install-file -Dfile=sqljdbc4.jar -DgroupId=com.microsoft.sqlserver -DartifactId=sqljdbc4 -Dversion=4.0 -Dpackaging=jar
```
to make maven aware of the jar but when I run mvn package afterwards, it still fails to find the jar.

**Comment by ligadata-william** [comment]
Assembly error on project SaveContainerDataComponent:
```
[error] 2 errors were encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
com/ligadata/keyvaluestore/DriverShim.class
com/ligadata/keyvaluestore/DriverShim.class
deduplicate: different file contents found in the following:
com/ligadata/keyvaluestore/JdbcClassLoader.class
com/ligadata/keyvaluestore/JdbcClassLoader.class
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:241)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:238)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (SaveContainerDataComponent/*:assembly) deduplicate: different file contents found in the following:
[error] com/ligadata/keyvaluestore/DriverShim.class
[error] com/ligadata/keyvaluestore/DriverShim.class
[error] deduplicate: different file contents found in the following:
[error] com/ligadata/keyvaluestore/JdbcClassLoader.class
[error] com/ligadata/keyvaluestore/JdbcClassLoader.class
[error] Total time: 257 s, completed Nov 7, 2016 5:29:35 PM
```
I'll fix this locally and try again.

**Comment by ligadata-william** [comment]
It looks like running mvn package on OutputUtils presents the same Java 8 dependency issue that existed in the GenerateKeys project.
```
MacBook-Pro-2:OutputUtils william$ mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building KafkaOutputAdapters 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ KafkaOutputAdapters ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 16 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ KafkaOutputAdapters ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 33 source files to /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[15,16] sun.misc.Signal is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[77,84] sun.misc.SignalHandler is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[15,16] sun.misc.Signal is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[77,84] sun.misc.SignalHandler is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[15,16] sun.misc.Signal is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[77,84] sun.misc.SignalHandler is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[15,16] sun.misc.Signal is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[77,84] sun.misc.SignalHandler is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/mail/MailProcessor.java:[15,11] sun.misc.BASE64Decoder is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/mail/MailProcessor.java:[15,42] sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/mail/util/SecretKeyFactoryImpl.java:[31,19] sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/mail/util/SecretKeyFactoryImpl.java:[32,19] sun.misc.BASE64Decoder is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/mail/util/SecretKeyFactoryImpl.java:[59,45] sun.misc.BASE64Encoder is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/mail/util/SecretKeyFactoryImpl.java:[60,45] sun.misc.BASE64Decoder is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[80,28] sun.misc.Signal is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[86,48] sun.misc.Signal is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/KafkaAdapter.java:[86,21] sun.misc.Signal is internal proprietary API and may be removed in a future release
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/GenerateKeys.java: /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/GenerateKeys.java uses or overrides a deprecated API.
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/GenerateKeys.java: Recompile with -Xlint:deprecation for details.
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/statusRecorders/KafkaStatusRecorder.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/statusRecorders/KafkaStatusRecorder.java: Recompile with -Xlint:unchecked for details.
[INFO] 21 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/DecryptUtils.java:[34,17] cannot find symbol
  symbol:   class Base64
  location: package java.util
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[19,36] cannot find symbol
  symbol:   class SQLServerBulkCSVFileRecord
  location: package com.microsoft.sqlserver.jdbc
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[20,36] cannot find symbol
  symbol:   class SQLServerBulkCopy
  location: package com.microsoft.sqlserver.jdbc
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/DecryptUtils.java:[34,17] cannot find symbol
  symbol:   class Base64
  location: package java.util
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[19,36] cannot find symbol
  symbol:   class SQLServerBulkCSVFileRecord
  location: package com.microsoft.sqlserver.jdbc
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[20,36] cannot find symbol
  symbol:   class SQLServerBulkCopy
  location: package com.microsoft.sqlserver.jdbc
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/DecryptUtils.java:[77,30] cannot find symbol
  symbol:   variable Base64
  location: class com.ligadata.adapters.DecryptUtils
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/DecryptUtils.java:[96,41] cannot find symbol
  symbol:   variable Base64
  location: class com.ligadata.adapters.DecryptUtils
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[170,17] cannot find symbol
  symbol:   class SQLServerBulkCSVFileRecord
  location: class com.ligadata.adapters.jdbc.SqlServerBulkCopySink
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[171,17] cannot find symbol
  symbol:   class SQLServerBulkCopy
  location: class com.ligadata.adapters.jdbc.SqlServerBulkCopySink
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[173,42] cannot find symbol
  symbol:   class SQLServerBulkCSVFileRecord
  location: class com.ligadata.adapters.jdbc.SqlServerBulkCopySink
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[186,40] cannot find symbol
  symbol:   class SQLServerBulkCopy
  location: class com.ligadata.adapters.jdbc.SqlServerBulkCopySink
[INFO] 12 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.183 s
[INFO] Finished at: 2016-11-07T17:59:08-08:00
[INFO] Final Memory: 30M/453M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project KafkaOutputAdapters: Compilation failure: Compilation failure:
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/DecryptUtils.java:[34,17] cannot find symbol
[ERROR] symbol:   class Base64
[ERROR] location: package java.util
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[19,36] cannot find symbol
[ERROR] symbol:   class SQLServerBulkCSVFileRecord
[ERROR] location: package com.microsoft.sqlserver.jdbc
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[20,36] cannot find symbol
[ERROR] symbol:   class SQLServerBulkCopy
[ERROR] location: package com.microsoft.sqlserver.jdbc
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/DecryptUtils.java:[34,17] cannot find symbol
[ERROR] symbol:   class Base64
[ERROR] location: package java.util
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[19,36] cannot find symbol
[ERROR] symbol:   class SQLServerBulkCSVFileRecord
[ERROR] location: package com.microsoft.sqlserver.jdbc
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[20,36] cannot find symbol
[ERROR] symbol:   class SQLServerBulkCopy
[ERROR] location: package com.microsoft.sqlserver.jdbc
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/DecryptUtils.java:[77,30] cannot find symbol
[ERROR] symbol:   variable Base64
[ERROR] location: class com.ligadata.adapters.DecryptUtils
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/DecryptUtils.java:[96,41] cannot find symbol
[ERROR] symbol:   variable Base64
[ERROR] location: class com.ligadata.adapters.DecryptUtils
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[170,17] cannot find symbol
[ERROR] symbol:   class SQLServerBulkCSVFileRecord
[ERROR] location: class com.ligadata.adapters.jdbc.SqlServerBulkCopySink
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[171,17] cannot find symbol
[ERROR] symbol:   class SQLServerBulkCopy
[ERROR] location: class com.ligadata.adapters.jdbc.SqlServerBulkCopySink
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[173,42] cannot find symbol
[ERROR] symbol:   class SQLServerBulkCSVFileRecord
[ERROR] location: class com.ligadata.adapters.jdbc.SqlServerBulkCopySink
[ERROR] /Users/william/dev/Kamanja/trunk/Utils/OutputUtils/src/main/java/com/ligadata/adapters/jdbc/SqlServerBulkCopySink.java:[186,40] cannot find symbol
[ERROR] symbol:   class SQLServerBulkCopy
[ERROR] location: class com.ligadata.adapters.jdbc.SqlServerBulkCopySink
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
MacBook-Pro-2:OutputUtils william$
```

**Comment by ligadata-ramana** [comment]
Removed the references to Base64. Please continue

**Pull request merged**
