### PR TITLE
Issue751,p2 issue, add a rest api to shutdown MetdataAPIService

### PR DESCRIPTION
**Pull request by ligadata-ramana**

### CODE REVIEW

**Comment by ligadata-william** [comment]
I'm getting an error when I start MetadataAPIService:
```
2015-12-28 12:08:33,868 main ERROR Unable to create file /media/home2/installKamanja/logs/KamanjaLog.log java.io.IOException: No such file or directory
```
It looks like there's something hard-coded.

**Comment by ligadata-william** [comment]
When I run 
```
curl https://localhost:8081/api/shutdown
```
I get the following error:
```
[ERROR] [12/28/2015 12:22:03.993] [metadata-api-service-akka.actor.default-dispatcher-8] [akka://metadata-api-service/user/metadata-api-service] Error during processing of request HttpRequest(GET,https://localhost:8081/api/shutdown,List(User-Agent: curl/7.43.0, Host: localhost:8081),Empty,HTTP/1.1)
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at com.ligadata.metadataapiservice.MetadataAPIService$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(MetadataAPIService.scala:67)
	at com.ligadata.metadataapiservice.MetadataAPIService$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(MetadataAPIService.scala:62)
	at spray.routing.ApplyConverterInstances$$anon$22$$anonfun$apply$1.apply(ApplyConverterInstances.scala:25)
	at spray.routing.ApplyConverterInstances$$anon$22$$anonfun$apply$1.apply(ApplyConverterInstances.scala:24)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:35)
	at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:33)
	at spray.routing.HttpServiceBase$class.runSealedRoute$1(HttpService.scala:36)
	at spray.routing.HttpServiceBase$$anonfun$runRoute$1.applyOrElse(HttpService.scala:46)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.ligadata.metadataapiservice.MetadataAPIServiceActor.aroundReceive(MetadataAPIService.scala:35)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ligadata-dan** [comment]
In MetadataAPIService

Used to be
  logger.debug("userid => " + user.get + ",password => xxxxx" + ",role => " + role+",modelname => "+modelname)

now its
  logger.debug("userid => " + user.get + ",password => xxxxx" + ",role => " + role.get + ",modelname => “+modelname.get

**Comment by ligadata-dan** [comment]
Willie,

I changed the code to treat those fields as Strings for now to unblock you.

**Comment by ligadata-ramana** [comment]
william, we added some more changes so I check for null/non-null for all three variables userid, role, modelname. This is a minor change on top what Dan has done before.

**Comment by ligadata-william** [comment]
I ran the command to shutdown and received a message indicating the service was being shutdown. However, it looks like even though the service was shut down, the process running that service is still running. I reproduced this by running MetadataAPIService in the foreground, then calling the shutdown command. Further curl commands give me a connection refused message (as I would expect) but I still see my console window is taken up by the MetadataAPIService process.

**Comment by ligadata-william** [comment]
Can one of the admins verify this patch?

**Comment by ligadata-william** [comment]
@ligadata-ramana last I ran this, the shutdown method caused a hang in my console window. Has this been resolved or does this still need to be fixed?

**Comment by ligadata-william** [comment]
Closing due to age.

**Pull request closed without merging**
