### PR TITLE
Fix P0 Issue 989

### PR DESCRIPTION
**Pull request by ligadata-rich**
The supplied fix will allow a pmml model to consume any proper subset of the available fields (except the empty set) in the supplied dataset.  See Issue #989

### CODE REVIEW

**Comment by ligadata-william** [comment]
@ligadata-rich do you have a copy of the pmml that unearthed this issue? I'd like to toss it into my tests.

**Comment by ligadata-rich** [comment]
here you go.

**Comment by ligadata-william** [comment]
Can one of the admins verify this patch?

**Comment by ligadata-william** [comment]
I still need to test this. I'm a bit behind.

**Pull request closed without merging**
