### PR TITLE
Fatafat 257

### PR DESCRIPTION
**Pull request by ligadata-pokuri**
1. Allowing multiple output adapters
2. If we specify any Output Message definitions, we are just sending output to the corresponding output adapter which are specified in Output message. If we don't have any output message definitions, we send the default output to all output adapters.
3. This may break exactly once. Not yet extensively tested that.
4. This branch is created on top of OutputMsgDefFixes branch.

### CODE REVIEW

**Comment by ligadata-william** [comment]
Do we support multiple output messages? I'm trying to set up a test with 3 output messages that each point to a different output queue. I we do support multiple output messages, how do I differentiate when to create each one? Do they need to be tied to a specific input message?

**Comment by ligadata-pokuri** [comment]
You can use the same input message & models or you can use different models & different input messages for each output message.

 

Ex: If you have two input messages called InputMessage1 & InputMessage2

If InputMessage1 has two models Model1 & Model2 and InputMessage2 has two more models Model3 & Model4.

 

You can try to define 4 output message definitions. 

OutputMsgDef1 can be populated from InputMessage1 & Model1

OutputMsgDef2 can be populated from InputMessage1 & Model2

OutputMsgDef3 can be populated from InputMessage2 & Model3

OutputMsgDef4 can be populated from InputMessage2 & Model4

 

For now you can do this simple test

 

Thanks

Pokuri

**Comment by ligadata-william** [comment]
Three output messages are working for multiple models/messages. However, when I'm expecting only one output message to be generated, I'm seeing three output messages (each to their individual output topic) generated with empty values. Some users may have issue with an output message always being generated. Is there a way to configure when an output message should be generated? It seems like output messages are generated for EVERY message and model instead of just the relevant messages/models.

**Comment by ligadata-pokuri** [comment]
Hi William,

 

I think we have some bug there. Just open another issue and assign it to tulasi. At this moment may be we will add some trigger point (associated input messages or something) to make these output messages generating output.

 

Finish the testing for this feature/bug supporting multiple output adapters.

 

Thanks

Pokuri

**Comment by ligadata-william** [comment]
issue https://github.com/ligaDATA/Kamanja/issues/784 opened.

**Comment by ligadata-william** [comment]
Given MessageA, ModelA and ModelB (both of which consume MessageA) and OutputMessageA (which is designed for output from MessageA, ModelA and ModelB) what is the expected result.
What I'm seeing is that with a single output message, all the results are being grouped together into a single output message. Do we want this to happen or do we want a single output message per model execution?

**Comment by ligadata-pokuri** [comment]
Output message definitions are prepared on after executing all the models at this moment. Just before sending the output to output adapter, we prepare the output message definition. So, it is not per model. It is after executing all the models.

 

We are going to introduce transformation section later, that simply handles the DAG however you want. But at this moment, output messages are prepared after executing all models. But if one model did not execute, but if the output message still requires the output of that model, then it will get from the most recent result from that model.

 

Thanks

Pokuri

**Comment by ligadata-william** [comment]
I'm seeing an issue with the output generated by one message with two models. The input message is as follows:
```
com.ligadata.tests.outputmessage.inputmessage1,11,This is message 1.1
```
Two models are executed upon receiving this message and are generating a single output message. This output message appears to be getting incorrect values for Model1.Message and Model2.Message
```
{
    "InputMessage1.Id": "11",
    "InputMessage1.Message": "This is message 1.1",
    "Model1.Id": "11",
    "Model1.Message": "11",  ----> This should be equal to InputMessage1.Message
    "Model2.Id": "11",
    "Model2.Message": "11"  ----> This should be equal to InputMessage1.Message
}
```

This issue may be somehow related to the model namespace issue Rich fixed in OutputMsgDefFixes.

**Comment by ligadata-pokuri** [comment]
Can you share the usecase what you are using? Send all metadata through mail

**Comment by ligadata-william** [comment]
Here is the use case:

**Comment by ligadata-pokuri** [comment]
@ligadata-william, I strongly request you to write java/scala models to test these features. Now we are going back and testing the functionality of other issues.

The feature we exposed here is supporting multiple output adapters. Now are extensively testing output message defintions & PMML XMLs. We are holding these feature merges just because of those issues.

**Comment by ligadata-rich** [comment]
With regard to the directed acyclic graphs that are to be introduced, it
should be noted that ALL models that may have dependencies upon other nodes
MUST consume the same incoming message... even if they are not using any
fields of it, but instead consuming just the derived values from other
(preceding) nodes in the graph.  If a member of the graph requires value(s)
that were derived by processing another message... as Pokuri says, then the
most recent result will simply be read from the last execution of that
model or those models.

Conceivably each model in the DAG could each emit their own result as well
as supply some computed value that is consumed by the down stream nodes in
the graph.  It sounds to me like we need to discuss this and nail down the
expected semantics (both what can be done now as well as what is ultimately
desired).  Let's discuss in the meeting tomorrow.

**Pull request merged**
