### PR TITLE
Berkley 1.5.3 flr 680

### PR DESCRIPTION
**Pull request by ligadata-saleh**

### CODE REVIEW

**Comment by ligadata-pokuri** [comment]
Hi @ligadata-saleh 
When we restart the adapter we use the same file to write the data. With the new changes are you taking care of it? It looks like you are creating a file with current timestamp. What happens when you restart. Are you writing into the same new file or creating another file or something else is happening?

And also are you sure you are checking HDFS down exception, etc before opening the new file?

**Comment by ligadata-saleh** [comment]
It will try with the defult file again for 5 times before creating a new file with timestamp , the only way to set the new generated file when starting the tool is updating the config file since we dont you any storage .

**Comment by ligadata-pokuri** [comment]
Hi @ligadata-saleh , we need to have predicted file name. And also the changes we need is, when we open the file we need to check what is the latest file we got created from this predicted file names.

**Comment by ligadata-saleh** [comment]
all changes are done as @ligadata-pokuri  requested , more information in https://ligadata.atlassian.net/browse/FLR-680

**Comment by ligadata-pokuri** [comment]
@ligadata-sridhar  & @ligadata-bruce , can you review this code. I reviewed before and suggested changes and @ligadata-saleh did the changes. Can you review it?

**Comment by ligadata-william** [comment]
@ligadata-saleh This branch needs to be based off branch 1.6.2-Berkley. Can you rebase and create a new pull request?

**Comment by ligadata-saleh** [comment]
closing this pull and open a new one on https://github.com/LigaData/Kamanja/pull/1621

**Pull request closed without merging**
