### PR TITLE
Output msg def fixes

### PR DESCRIPTION
**Pull request by ligadata-pokuri**
Fixed couple of issues in Output Message Definition path.

This branch is created on top of MsgKVFormat.

We still have issues with if we have namespace more than one word.

### CODE REVIEW

**Comment by ligadata-pokuri** [comment]
@ligadata-william, I fixed the issues with namespace containing more than one word (i.e. like com.ligadata.kamanja.models). Now you can test it. I am not going to make any more changes in this branch

**Comment by ligadata-pokuri** [comment]
@ligadata-william, Just throwing error to parent and changed little bit to detect fixed/mapped. You can test both test cases (fixed/mapped).

**Comment by ligadata-william** [comment]
I've got an error with creating the output message after the model executes. The output message is created, however, anything referencing the model is generated as an empty string. I am testing this with a model that is using a custom namespace.

Full Input Message Name: com.ligadata.tests.outputmessage.Car
Full Model Name:               com.ligadata.tests.outputmessage.OutputMessageTest
Output Message Format: 
```
"OutputFormat": "{ \"Car.Vin_Number\": \"${com.ligadata.tests.outputmessage.Car.Vin_Number}\", \"Car.Make\": \"${com.ligadata.tests.outputmessage.Car.Make}\", \"Car.Model\": \"${com.ligadata.tests.outputmessage.Car.Model}\", \"Car.Year\": \"${com.ligadata.tests.outputmessage.Car.Year}\", \"OutputMessageTest.vinNumber\": \"${com.ligadata.tests.outputmessage.OutputMessageTest.vinNumber}\", \"OutputMessageTest.carMake\": \"${com.ligadata.tests.outputmessage.OutputMessageTest.carMake}\", \"OutputMessageTest.carModel\": \"${com.ligadata.tests.outputmessage.OutputMessageTest.carModel}\", \"OutputMessageTest.carYear\": \"${com.ligadata.tests.outputmessage.OutputMessageTest.carYear}\" }"
```

I will change the model to use the default System namespace and update the output message definition accordingly to see if this is a namespace parsing issue.

**Comment by ligadata-william** [comment]
@ligadata-tulasi Does the output message format require a model's namespace to be specified or do we simply use the name of the model sans namespace?

**Comment by ligadata-pokuri** [comment]
can you send/attach the usecase you are using ?

**Comment by ligadata-tulasi** [comment]
The output format requires the models namespace, you need to give  namespace.modelname.attribute  format.

**Comment by ligadata-william** [comment]
Attached via email.

**Comment by ligadata-william** [comment]
Sorry,

I have to send again. I didn’t change all the ‘System’s” in the namespace in the last tar.

**Comment by ligadata-william** [comment]
Verified it works as expected when using System for the model's namespace:
```
{
    "Car.Vin_Number": "V1234HKASDF91FA6",
    "Car.Make": "Toyota",
    "Car.Model": "Camry",
    "Car.Year": "2012",
    "OutputMessageTest.vinNumber": "V1234HKASDF91FA6",
    "OutputMessageTest.carMake": "Toyota",
    "OutputMessageTest.carModel": "Camry",
    "OutputMessageTest.carYear": "2012"
}
```
When I use a custom namespace, I get this:
```
{
    "Car.Vin_Number": "V1234HKASDF91FA6",
    "Car.Make": "Toyota",
    "Car.Model": "Camry",
    "Car.Year": "2012",
    "OutputMessageTest.vinNumber": "",
    "OutputMessageTest.carMake": "",
    "OutputMessageTest.carModel": "",
    "OutputMessageTest.carYear": ""
}
```

**Comment by ligadata-pokuri** [comment]
Can you use scala/java model for now to use namespace with more than one word.

The issue is, PMML model is still generating model name as System even though if you give something else. I don't even see the version number in package name. Just open another issue for this and assign it to dan/rich.

Here is the one it is generating in scala class

package com.ligadata.tests.outputmessage

...............

object OutputMessageTest extends ModelBaseObj {
    override def ModelName(): String = "System.OutputMessageTest"
    override def Version(): String = "1000000"
    val validMessages = Array("com.ligadata.tests.outputmessage.V1000000.Car")
    override def IsValidMessage(msg: MessageContainerBase): Boolean = {
        validMessages.filter( m => m == msg.getClass.getName).size > 0
    }

    override def CreateResultObject(): ModelResultBase = new MappedModelResults();

    override def CreateNewModel(mdlCtxt: ModelContext): ModelBase =
    {
           new OutputMessageTest(mdlCtxt, this)
    }

}

...............

**Comment by ligadata-pokuri** [comment]
If I don't add Output message definition, this is the output I am getting

**Comment by ligadata-rich** [comment]
I believe that there was a version generated at one point in the package,
but was purposely taken out.  I don't recall the exact thinking there.  Dan?

In order to get a different namespace, the name of the application in the
header section must have a specific namespace there.  For example, this
header:

    <Header copyright="Medco Corp. Copyright 2014" description="COPD Risk
Assessment">
        <Application name="COPDRiskAssessmentNmSpc" version="00.01.00"/>
    </Header>

will produce a system.COPDRiskAssessmentNmSpc for the model.

The following should produce your custom namespace:

    <Header copyright="Medco Corp. Copyright 2014" description="COPD Risk
Assessment">
        <Application name="com.medco.pmml.COPDRiskAssessmentNmSpc"
version="00.01.00"/>
    </Header>

In the example, the namespace would be com.medco.pmml and the model name is
COPDRiskAssessmentNmSpc


Here is the logic:

/** split the namespace given in the application name attribute (if
any) from the name... when no
 *  namespace prefix, default to "System" */
val (nmspc, name) : (String, String) = if (headerNode.name != null &&
headerNode.name.size > 0) {
 val buffer : StringBuilder = new StringBuilder
 val nmNodes : Array[String] = headerNode.name.split('.').map(_.trim)
 if (nmNodes.size > 1) {
  val nmPart : String = nmNodes.last
  val nmspcPart : String = nmNodes.takeWhile(_ !=
nmPart).addString(buffer, ".").toString
  buffer.clear
  (nmspcPart,nmPart)
 } else {
  ("System", headerNode.name)
 }
} else {
 PmmlError.logError(ctx, s"Incredibly the PmmlApplication name
attribute is not specified!")
 ("","")
}

**Comment by ligadata-william** [comment]
In the tests I was running, the model name space was designed as such. When
added to metadata it showed the correct name space and model name.

**Comment by ligadata-pokuri** [comment]
can you generate the output without output message definition and see the model name what you are getting? The internal name which returns by model when we call getModelName is System.xxxxxx

**Comment by ligadata-pokuri** [comment]
can you generate the output without output message definition and see the model name what you are getting? The internal name which returns by model when we call getModelName is System.xxxxxx

**Comment by ligadata-william** [comment]
I took a look at the scala being generated and the package name is correct but getModelDef is still showing system.

I have opened issue #781

**Comment by ligadata-william** [comment]
If I don't add an output message, I don't see any output produced.

**Comment by ligadata-pokuri** [comment]
I am getting it to output queue. Can you share your screen, so we can go thru what is going on

**Comment by ligadata-william** [comment]
A mistake on my end, I forgot to revert some configuration changes I was using to test another branch. I'm now getting output without the output message.

**Comment by ligadata-william** [comment]
The model name is showing incorrectly on the output. The ModelName shows as System.OutputMessageTest:
```
{
    "ModelsResult": [
        {
            "ModelName": "System.OutputMessageTest",
            "ModelVersion": "1000000",
            "uniqKey": "{\"Version\":1,\"Type\":\"Kafka\",\"Name\":\"testin_1\",\"TopicName\":\"testin_1\",\"PartitionId\":0}",
            "uniqVal": "{\"Version\":1,\"Offset\":0}",
            "xformedMsgCntr": 1,
            "totalXformedMsgs": 1,
            "output": [
                {
                    "Name": "TestHit",
                    "Value": "1"
                },
                {
                    "Name": "carYear",
                    "Value": "2012"
                },
                {
                    "Name": "vinNumber",
                    "Value": "V1234HKASDF91FA6"
                },
                {
                    "Name": "carModel",
                    "Value": "Camry"
                },
                {
                    "Name": "carMake",
                    "Value": "Toyota"
                }
            ]
        }
    ]
}
```
but during model compilation I see this:
```
 INFO [Thread-12-EventThread] - Created Model:com.ligadata.tests.outputmessage.outputmessagetest
```
and this:
API Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : "Map()",
    "Result Description" : "Model Added Successfully:com.ligadata.tests.outputmessage.outputmessagetest.000000000001000000"
  }
}

**Comment by ligadata-pokuri** [comment]
you can attach this information for Bug#781

**Comment by ligadata-william** [comment]
I modified the existing test at https://github.com/ligaDATA/KamanjaAutomation/blob/master/TestSetupManager/src/test/scala/com/ligadata/automation/tests/metadata/OutputMessageTests.scala to include namespaces to test the fixes here.

**Pull request merged**
