### PR TITLE
Removed build.sbt and moved all relevant contents int project/Build.s…

### PR DESCRIPTION
**Pull request by ligadata-william**
…cala. Original structure remains intact.

Adding TestConfigs.scala and TestSettings.scala to work in conjunction with Build.scala to apply new test settings to all projects.

USAGE:

Tests should go in the following directories:
Unit Tests:             <ModuleName>/src/test/scala
Integration Tests:  <ModuleName>/src/it/scala
End to End Tests: <ModuleName>/src/e2e/scala

### CODE REVIEW

**Comment by ligadata-william** [comment]
@ligadata-pokuri please assign this to someone to review if you don't want to do it.

**Comment by ligadata-pokuri** [comment]
Hi William,

Moving to build.sbt to Build.scala has any advantages? Can you place the links here for the advantage?

Because Haitham is changing it a lot for few fat jars. Need to make sure he is getting this information before he make final changes.

**Comment by ligadata-william** [comment]
Hey Pokuri,

To make it a smoother transition for Haitham, I can switch it back to
build.sbt for now. I don't think it's absolutely necessary for this to work.

**Comment by ligadata-william** [comment]
@ligadata-pokuri I've removed the Build.scala file and replaced it with build.sbt again. It works for me as expected. To run the different types of tests:

Unit Tests
```
sbt test
```
Integration Tests
```
sbt it:test
```
End to End Tests
```
sbt e2e:test
```

**Comment by ligadata-william** [comment]
This is included in #1002.

**Pull request closed without merging**
