### PR TITLE
1.5.3 phoenix avro support

### PR DESCRIPTION
**Pull request by ligadata-pokuri**
Added avro support.

We are simply providing AVRO & its codec to Compression in smart file output adapter config.

Here is the sample for full adapter config

    {
      "Name": "SmartFileOutputAdapter",
      "TypeString": "Output",
      "TenantId": "tenant1",
      "ClassName": "com.ligadata.OutputAdapters.SmartFileProducer$",
      "DependencyJars": [
      ],
      "AdapterSpecificCfg": {
        "Uri": "file://tmp/output",
        "FileNamePrefix": "Data",
        "PartitionBuckets": "1",
        "RolloverInterval": "1",
        "UseTypeFullNameForPartition": false,
        "Compression": "avro/snappy"
      }
    },
If you don't want to specify any codec, just specify this
"Compression": "avro"

If you specify snappy codec, use this
"Compression": "avro/snappy"

### CODE REVIEW

**Comment by ligadata-william** [comment]
When I configure compression as "avro/snappy" the value for the fields appears to be incorrect:
```
{
	"type": "record",
	"name": "outmsg1",
	"namespace": "com.ligadata.kamanja.samples.messages",
	"fields": [{
		"name": "id",
		"type": ["int", "null"]
	}, {
		"name": "name",
		"type": ["string", "null"]
	}]
}
```
It shows "name" as id and name correctly, and the "type" seems to be displaying the correct data type but fails to display the actual values correlating with the output.

**Comment by ligadata-william** [comment]
After output is generated, the following exception is spammed until the engine is shutdown:
```
WARN [pool-13-thread-1] - Failed to rollover.
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
	at org.apache.avro.file.SnappyCodec.compress(SnappyCodec.java:43) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at org.apache.avro.file.DataFileStream$DataBlock.compressUsing(DataFileStream.java:349) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at org.apache.avro.file.DataFileWriter.writeBlock(DataFileWriter.java:348) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at org.apache.avro.file.DataFileWriter.sync(DataFileWriter.java:360) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at org.apache.avro.file.DataFileWriter.flush(DataFileWriter.java:367) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.OutputAdapters.StreamPartitionFile.flush(StreamPartitionFile.scala:348) ~[KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.OutputAdapters.SmartFileProducer$$anonfun$com$ligadata$OutputAdapters$SmartFileProducer$$rolloverFiles$2.apply(SmartFileProducer.scala:595) ~[KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.OutputAdapters.SmartFileProducer$$anonfun$com$ligadata$OutputAdapters$SmartFileProducer$$rolloverFiles$2.apply(SmartFileProducer.scala:590) ~[KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777) ~[ExtDependencyLibs2_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.OutputAdapters.SmartFileProducer.com$ligadata$OutputAdapters$SmartFileProducer$$rolloverFiles(SmartFileProducer.scala:590) ~[KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
	at com.ligadata.OutputAdapters.SmartFileProducer$$anon$2.run(SmartFileProducer.scala:520) [KamanjaInternalDeps_2.11-1.5.3.jar:1.5.3]
	at scala.actors.threadpool.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1060) [ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at scala.actors.threadpool.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574) [ExtDependencyLibs_2.11-1.5.3.jar:1.5.3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by ligadata-william** [comment]
It looks like with snappy, the output values are being displayed separately and require decompression in order to see (or so I theorize). I'm going to try setting the URI to an HDFS node so I can use -text to see if the results are displayed correctly.

**Comment by ligadata-william** [comment]
Ok, actual results of testing this time.

@ligadata-pokuri Configuring with compression as "avro" and outputting to HDFS, I am able to use the command:
```
hdfs dfs -text /tmp/output/outmsg1/HelloWorld1-0-20170314T1556.avro
```
to print output
```
{"id":{"int":1},"name":{"string":"World"}}
{"id":{"int":50},"name":{"string":"Hello"}}
```

However, when I switch compression to "avro/snappy", there is no output because of the exception in the previous comment.

**Comment by ligadata-pokuri** [comment]
Hi @ligadata-william ,
Can you open a bug for Snappy and proceed with other testing?

What I did was, I downloaded the filed from HDFS to local and did the testing like this

java -jar avro-tools-1.8.1.jar tojson /tmp/output/outmsg1/Data1-0-20170312T0218.avro 

That will display all the values in JSON format.

**Comment by ligadata-pokuri** [comment]
Hi @ligadata-william 

where did you see this? Is it showing like that when you do hdfs dfs -text /tmp/output/outmsg1/HelloWorld1-0-20170314T1556.avro?

When I configure compression as "avro/snappy" the value for the fields appears to be incorrect:

{
	"type": "record",
	"name": "outmsg1",
	"namespace": "com.ligadata.kamanja.samples.messages",
	"fields": [{
		"name": "id",
		"type": ["int", "null"]
	}, {
		"name": "name",
		"type": ["string", "null"]
	}]
}
It shows "name" as id and name correctly, and the "type" seems to be displaying the correct data type but fails to display the actual values correlating with the output.

**Comment by ligadata-william** [comment]
@ligadata-pokuri the json structure showing type, name, naemspace, etc, is the avro schema that is displayed if I don't use hdfs dfs -text. It's the compressed avro. As far as that is concerned, the schema is correct.
However, for avro/snappy, there isn't any actual output. due the the exception I commented earlier.
Like I said, when I run with just "avro", the command:
```
hdfs dfs -text /tmp/output/outmsg1/HelloWorld1-0-20170314T1556.avro
```
produces
```
{"id":{"int":1},"name":{"string":"World"}}
{"id":{"int":50},"name":{"string":"Hello"}}
```
However, when I run with "avro/snappy", the two lines:
```
{"id":{"int":1},"name":{"string":"World"}}
{"id":{"int":50},"name":{"string":"Hello"}}
```
do NOT appear.

**Comment by ligadata-william** [comment]
See #1532 for avro/snappy issue.

**Pull request merged**
