### PR TITLE
V13 monitor enhancements

### PR DESCRIPTION
**Pull request by ligadata-dan**
@ligadata-william @ligadata-pokuri 

This should have the code from pokuri's branch.   So you can test both without changing branches.

### CODE REVIEW

**Comment by ligadata-tulasi** [comment]
I have found an issue about the Last Failure and Last Recovery metrics, the issue unable to get the time when the kafka server is stopped. Dan is checking the issue.

**Comment by ligadata-pokuri** [comment]
Fixed issue https://github.com/ligaDATA/Kamanja/issues/907

**Comment by ligadata-dan** [comment]
fixed issue #906

**Comment by ligadata-dan** [comment]
Fixed issue #908

**Pull request merged**
