### PR TITLE
Issue898

### PR DESCRIPTION
**Pull request by ligadata-saleh**
Changes to ClusterInstall to make soft links instead of removing the directory data #898

### CODE REVIEW

**Comment by ligadata-william** [comment]
When I echo my $PATH, I get the following:
```
echo $PATH
/tmp/Kamanja/ClusterInstall:/opt/local/bin:/opt/local/sbin:/tmp/Kamanja/ClusterInstall:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/will/.svm/current/rt/bin:/usr/local/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home//bin:/usr/local/Cellar/kafka/0.8.2.1/bin:/Users/will/dev/kamanja/trunk/Pmml/Scripts/extractUdfLibMetadata/src/main/scala:Pmml/Scripts/sbtProjDependencies/src/main/scala:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/will/dev/kamanja/trunk/Utils/NodeInfoExtract/target/scala-2.10:/tmp/Kamanja/bin
```
However, no matter what I try, unless I'm in the ClusterInstall directory, I get the following error:
```
/tmp/Kamanja/ClusterInstall/KamanjaClusterInstall.sh: line 320: ./NodeInfoExtract-1.0: No such file or directory
```

This appears to be due to the change of the script from running
```
NodeInfoExtract-1.0 --MetadataAPIConfig "$metadataAPIConfig" --NodeConfigPath "$nodeConfigPath" --workDir "$workDir" --ipFileName "$ipFile" --ipPathPairFileName "$ipPathPairFile" --ipIdCfgTargPathQuartetFileName "$ipIdCfgTargPathQuartetFileName"  --installDir "$installDir" --clusterId "$clusterId"
```
to
```
./NodeInfoExtract-1.0 --MetadataAPIConfig "$metadataAPIConfig" --NodeConfigPath "$nodeConfigPath" --workDir "$workDir" --ipFileName "$ipFile" --ipPathPairFileName "$ipPathPairFile" --ipIdCfgTargPathQuartetFileName "$ipIdCfgTargPathQuartetFileName"  --installDir "$installDir" --clusterId "$clusterId"
```

**Comment by ligadata-william** [comment]
When I run the script the first time (no previous installation), two directories are created, Kamanja and Kamanja_<Date>. It seems like having two installations on every single node in the cluster is going to be a bit overkill, especially with them being about 800Mb. Shouldn't a backup folder be created only on subsequent installations?

**Comment by ligadata-pokuri** [comment]
Hi William,

 

Every install should create one Directory and Kamanja should point to that with soft link.

 

Thanks

Pokuri

**Comment by ligadata-william** [comment]
There are two directories created and I don't know the location of the soft link. Where is the soft link placed?

**Comment by ligadata-william** [comment]
When I type in kamanja after running cluster install, there is no auto-complete indicating that the soft link either doesn't exist or it isn't placed in a directory on my $PATH.

**Comment by ligadata-saleh** [comment]
its the same install directory that u pass to the command , and the script
rename the old directory with "Kamanja_pre_<date>"  and add a new directory
with "Kamanja_<date>" the soft link will point to the new directory that is
without the pre  .

**Comment by ligadata-william** [comment]
That's the problem that I am trying to convey, there is no "old directory" to rename. Two brand new directories are created on a fresh install. This shouldn't happen. As for the soft link, I didn't notice it in cluster install, I'll have to run it again the next time I test.

The change in the way NodeInfoExtract is executed is still a problem.

**Comment by ligadata-william** [comment]
After talking to Pokuri, he tells me the entire Kamanja directory is a soft link. I'll take another look at it later today.

**Comment by ligadata-saleh** [comment]
as far as i know i didnt change anything is the NodeInfoExtract , the task
issue was stopping the script from deleting the old directory when
installing a new version of Kamanja

**Pull request merged**
