### PR TITLE
GetHealthCheck will return a valid JSON formatted RESULT DATA

### PR DESCRIPTION
**Pull request by ligadata-dan**

### CODE REVIEW

**Comment by ligadata-dan** [comment]
@ligadata-william 

Merle.. This addressed 741 and 738 ....   Remember from CURL you gotta escape "

I found that putting garbage into an array causes a funky FasterXML exception,, which will drive the generic exception path.

Putting a unescaped, ["2"] for example is an exptected exception..

They do the same recovery, but one will create an error message while the other a warning.

**Comment by ligadata-william** [comment]
I'm getting an error every time I try to run a GET call on this branch:
```
[ERROR] [10/16/2015 10:39:12.060] [metadata-api-service-akka.actor.default-dispatcher-4] [akka://metadata-api-service/user/metadata-api-service] Error during processing of request HttpRequest(GET,https://localhost:8081/api/heartbeat,List(User-Agent: curl/7.43.0, Host: localhost:8081),Empty,HTTP/1.1)
com.ligadata.Exceptions.InvalidArgumentException: Invalid Metadata Object Name, Unable to parse Namespace.Name.Version
	at com.ligadata.kamanja.metadata.Utils$.parseNameToken(Utils.scala:33)
	at com.ligadata.metadataapiservice.MetadataAPIService$class.createGetArg(MetadataAPIService.scala:451)
	at com.ligadata.metadataapiservice.MetadataAPIService$class.verifyInput(MetadataAPIService.scala:427)
	at com.ligadata.metadataapiservice.MetadataAPIService$class.com$ligadata$metadataapiservice$MetadataAPIService$$processGetObjectRequest(MetadataAPIService.scala:388)
	at com.ligadata.metadataapiservice.MetadataAPIService$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4$$anonfun$apply$7.apply(MetadataAPIService.scala:79)
	at com.ligadata.metadataapiservice.MetadataAPIService$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$apply$4$$anonfun$apply$7.apply(MetadataAPIService.scala:79)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
	at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
	at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:35)
	at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:33)
	at spray.routing.HttpServiceBase$class.runSealedRoute$1(HttpService.scala:36)
	at spray.routing.HttpServiceBase$$anonfun$runRoute$1.applyOrElse(HttpService.scala:46)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.ligadata.metadataapiservice.MetadataAPIServiceActor.aroundReceive(MetadataAPIService.scala:35)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I also tried running some other get calls on metadata objects and found that any time I don't have a get call in the format curl -k https://localhost:8081/api/<type>/<objectKey> it fails, including when I use /api/heartbeat.

**Comment by ligadata-william** [comment]
Hey @ligadata-dan, if you remember before your vacation, there was still an issue on this branch regarding proper error handling of bad URLs. Talk to me if you need to look at it again.

**Comment by ligadata-dan** [comment]
@ligadata-william 
Merle!!!!  Try this..........

**Pull request merged**
