### PR TITLE
Add recovery changes in a new branch

### PR DESCRIPTION
**Pull request by ligadata-dan**
@ligadata-william 

I have broken up the previous pull request, so now it only has the MQ related changes..

### CODE REVIEW

**Comment by ligadata-dan** [comment]
@ligadata-william 

Dhaval's instructions.

**Comment by ligadata-dan** [comment]
Hi,

Please find the commands used on wow rack server for running the MQ manager:
export CLASSPATH=""
export CLASSPATH="javax.jms.jar:com.ibm.msg.client.provider.jar:com.ibm.msg.client.jms.jar:com.ibm.msg.client.jms.internal.jar:com.ibm.msg.client.commonservices.jar:com.ibm.mqjms.jar:"

export CLASSPATH="/opt/mqm/java/lib/com.ibm.mqjms.jar:/opt/mqm/samp/jms/samples:$CLASSPATH"

commands
1.
Check if MQ Manager running. If not start it. Name is QMA.
runmqsc QMA
ALTER QMGR CHLAUTH(DISABLED)

2.
/opt/mqm/samp/jms/samples
java JmsConsumer -m QMA -d QUEUE1 -h localhost -p 1414
3.
cd /opt/mqm/samp/bin
./amqsput QUEUE1 QMA

**Comment by ligadata-william** [comment]
Can one of the admins verify this patch?

**Comment by ligadata-william** [comment]
This has already been merged in another branch. closing.

**Pull request closed without merging**
