### PR TITLE
Sprint8 features with jpmml

### PR DESCRIPTION
**Pull request by ligadata-rich**
Fatafat218 and related describe the work overall.

Tests are found in Pmml/JpmmlAdapter for new Jpmml tests and regressions of prior models (most) are in Pmml/PmmlUdfs.  

See  https://github.com/ligaDATA/Kamanja/commit/ca016b045a4ea58b751f8dca7734805965b5787e for exact locations of tests.

### CODE REVIEW

**Comment by ligadata-rich** [comment]
the jpmml tests (see Pmml/JpmmlAdapter/src/main/resources/JpmmlTestCases.md) and
existing tests (see Pmml/trunk/Pmml/PmmlUdfs/src/test/resources/RegressionTestCases.md)

**Comment by ligadata-william** [comment]
Getting an error after the latest merge:
```
 INFO [Thread-13] - Created FactoryOfModelInstanceFactory:com.ligadata.factoryofmodelinstancefactory.jarfactoryofmodelinstancefactory
ERROR [Thread-13] - Jar scala-reflect-2.11.0.jar not found
```
Looks like MetadataLoad.scala is using 2.11.0.jar instead of 2.11.7 like it should.

**Comment by ligadata-william** [comment]
Same thing with scala-compiler. MetadataLoad.scala references 2.11.0 instead of 2.11.7.

**Comment by ligadata-pokuri** [comment]
Hi Rich,

 

We need all the non-required  jars from jars list when you register JpmmlFactoryOfModelInstanceFactory

**Comment by ligadata-ahmad** [comment]
adding kpmml using this command 
./kamanja ../config/MetadataAPIConfig.properties add model kpmml ../input/SampleApplications/metadata/model/KPMML_Model_HelloWorld.xml

failed  with this error message :

Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "One or more PMML arguments have not been specified... modelName = null, version = null, input = <!--\n  ~ Copyright 2015 ligaDATA\n  ~\n  ~ Licensed under the Apache License, Version 2.0 (the \"License\");\n  ~ you may not use this file except in compliance with the License.\n  ~ You may obtain a copy error = Failed to Add Model"
  }
}

**Comment by ligadata-ahmad** [comment]
I got the same error when adding kpmml using MetadataAPI menu 

[2] /data/Ahmed/Jpmml-Test/kamanja/input/SampleApplications/metadata/model/KPMML_Model_HelloWorld.xml
[3] Main Menu

Enter your choice: 2
Results as json string =>
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "One or more PMML arguments have not been specified... modelName = null, version = null, input = <!--\n  ~ Copyright 2015 ligaDATA\n  ~\n  ~ Licensed under the Apache License, Version 2.0 (the \"License\");\n  ~ you may not use this file except in compliance with the License.\n  ~ You may obtain a copy error = Failed to Add Model"
  }
}

**Comment by ligadata-rich** [comment]
As I mentioned on the IM to Pokuri earlier today, my strategy is to let the
sbt tell me which jars a given project requires (e.g.,
JpmmlFactoryOfModelInstanceFactory).  When I run it, I get these jars as
required:

jpmmlfactoryofmodelinstancefactory_2.11-1.0.jar, metadata_2.11-1.0.jar,
exceptions_2.11-1.0.jar, kamanjabase_2.11-1.0.jar,
kamanjautils_2.11-1.0.jar, kvbase_2.11-0.1.0.jar,
datadelimiters_2.11-1.0.jar, scala-library-2.11.7.jar, log4j-api-2.4.1.jar,
log4j-core-2.4.1.jar, joda-convert-1.6.jar, json4s-native_2.11-3.2.9.jar,
json4s-core_2.11-3.2.9.jar, json4s-ast_2.11-3.2.9.jar, paranamer-2.6.jar,
scalap-2.11.0.jar, scala-compiler-2.11.0.jar, scala-reflect-2.11.0.jar,
scala-xml_2.11-1.0.1.jar, scala-parser-combinators_2.11-1.0.1.jar,
json4s-jackson_2.11-3.2.9.jar, jackson-databind-2.3.1.jar,
jackson-annotations-2.3.0.jar, jackson-core-2.3.1.jar, jsr305-1.3.9.jar,
pmml-evaluator-1.2.9.jar, pmml-model-1.2.9.jar, pmml-agent-1.2.9.jar,
pmml-schema-1.2.9.jar, guava-19.0.jar, joda-time-2.9.1.jar,
commons-math3-3.6.jar

Notice "scala-compiler-2.11.0.jar, scala-reflect-2.11.0.jar," in the list.
Why this is so on my machine and not yours William is an enigma wrapped in
a mystery.  I suspect that the "%%" specification allows a number of jars
to fill the bill and your machine had different ones than mine... but hey I
have no clue really.

I have opened a jira story on this so we won't forget it.   This dependency
thing is problematical for sure, and it will likely be experienced by
others (customers).

**Comment by ligadata-ahmad** [comment]
I am using HBASE for testing this branch .  adding messages , containers
and models works fine but when starting the engine I got the following
error.

DEBUG [main] - Storage configuration:{"StoreType": "hbase","SchemaName":
"metadata","Location": "localhost"}
DEBUG [main] - HBase configuration:{"StoreType": "hbase","SchemaName":
"metadata","Location": "localhost"}
log4j:WARN No appenders could be found for logger
(org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for
more info.
 INFO [main] - HBase info => Hosts:localhost,
Namespace:metadata,autoCreateTables:YES
ERROR [main] - Failed to create table
metadata:config_objects:java.lang.IllegalAccessError: tried to access
method com.google.common.base.Stopwatch.<init>()V from class
org.apache.hadoop.hbase.zookeeper.MetaTableLocator
ERROR [main] - Failed to fetch data from the table
metadata:config_objects:Failed to create table
 metadata:config_objects:Failed to execute create/drop operations on
Database
DEBUG [main] -
StackTrace:com.ligadata.Exceptions.StorageDMLException: Failed to execute
select/insert/delete/update operation on Database
        at com.ligadata.keyvaluestore.HBaseAdapter.com
$ligadata$keyvaluestore$HBaseAdapter$$CreateDMLException(HBaseAdapter.scala:78)
        at
com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:858)
        at
com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllConfigObjectsIntoCache(MetadataAPIImpl.scala:5343)
        at
com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:5423)
        at
com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:7845)
        at
com.ligadata.KamanjaManager.KamanjaMetadata$.InitBootstrap(KamanjaMetadata.scala:818)
        at
com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:414)
        at
com.ligadata.KamanjaManager.KamanjaManager.run(KamanjaManager.scala:579)
        at
com.ligadata.KamanjaManager.OleService$.main(KamanjaManager.scala:764)
        at com.ligadata.KamanjaManager.OleService.main(KamanjaManager.scala)
Caused by: java.lang.Exception: Failed to create table
 metadata:config_objects:Failed to execute create/drop operations on
Database
        at com.ligadata.keyvaluestore.HBaseAdapter.com
$ligadata$keyvaluestore$HBaseAdapter$$CheckTableExists(HBaseAdapter.scala:307)
        at
com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:844)
        ... 8 more

DEBUG [main] - Assuming bootstrap... No config objects in persistent store
ERROR [main] - Failed to create table
metadata:transaction_id:java.lang.IllegalAccessError: tried to access
method com.google.common.base.Stopwatch.<init>()V from class
org.apache.hadoop.hbase.zookeeper.MetaTableLocator
ERROR [main] - Failed to fetch data from the table
metadata:transaction_id:Failed to create table
 metadata:transaction_id:Failed to execute create/drop operations on
Database
DEBUG [main] - General Exception: Error => Failed to execute
select/insert/delete/update operation on Database
DEBUG [main] - Max Transaction Id => 0
ERROR [main] - Failed to create table
metadata:model_config_objects:java.lang.IllegalAccessError: tried to access
method com.google.common.base.Stopwatch.<init>()V from class
org.apache.hadoop.hbase.zookeeper.MetaTableLocator
ERROR [main] - Failed to fetch data from the table
metadata:model_config_objects:Failed to create table
 metadata:model_config_objects:Failed to execute create/drop operations on
Database
DEBUG [main] -
StackTrace:com.ligadata.Exceptions.StorageDMLException: Failed to execute
select/insert/delete/update operation on Database
        at com.ligadata.keyvaluestore.HBaseAdapter.com
$ligadata$keyvaluestore$HBaseAdapter$$CreateDMLException(HBaseAdapter.scala:78)
        at
com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:858)
        at
com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllModelConfigsIntoCache(MetadataAPIImpl.scala:5403)
        at
com.ligadata.MetadataAPI.MetadataAPIImpl$.LoadAllObjectsIntoCache(MetadataAPIImpl.scala:5431)
        at
com.ligadata.MetadataAPI.MetadataAPIImpl$.InitMdMgrFromBootStrap(MetadataAPIImpl.scala:7845)
        at
com.ligadata.KamanjaManager.KamanjaMetadata$.InitBootstrap(KamanjaMetadata.scala:818)
        at
com.ligadata.KamanjaManager.KamanjaManager.initialize(KamanjaManager.scala:414)
        at
com.ligadata.KamanjaManager.KamanjaManager.run(KamanjaManager.scala:579)
        at
com.ligadata.KamanjaManager.OleService$.main(KamanjaManager.scala:764)
        at com.ligadata.KamanjaManager.OleService.main(KamanjaManager.scala)
Caused by: java.lang.Exception: Failed to create table
 metadata:model_config_objects:Failed to execute create/drop operations on
Database
        at com.ligadata.keyvaluestore.HBaseAdapter.com
$ligadata$keyvaluestore$HBaseAdapter$$CheckTableExists(HBaseAdapter.scala:307)
        at
com.ligadata.keyvaluestore.HBaseAdapter.get(HBaseAdapter.scala:844)
        ... 8 more

I can start the engine successfully in dev branch .
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ligadata-ahmad** [comment]
Hi @ligadata-rich 
adding kpmml model using command  is working now .but we still have issue when adding kpmml model using MetadataAPI menu .

Enter your choice: 1
Pick a Model Definition file(pmml) from below choices
[1] /data/Ahmed/test/kamanja/input/SampleApplications/metadata/model/COPDRiskAssessmentv2_Medical.xml
[2] /data/Ahmed/test/kamanja/input/SampleApplications/metadata/model/KPMML_Model_HelloWorld.xml
[3] Main Menu

Enter your choice: 2
Results as json string =>
{
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "One or more PMML arguments have not been specified... modelName = null, version = null, input = <!--\n  ~ Copyright 2015 ligaDATA\n  ~\n  ~ Licensed under the Apache License, Version 2.0 (the \"License\");\n  ~ you may not use this file except in compliance with the License.\n  ~ You may obtain a copy error = Failed to Add Model"
  }
}

**Comment by ligadata-krishna** [comment]
Ahmad,

Why don't you look at what API call is being used by menu and see if you
can fix it.

Thanks
-Krishna

**Comment by ligadata-ahmad** [comment]
@ligadata-krishna  sure. I will do that .

**Comment by ligadata-rich** [comment]
Looks like I missed another one ... code is executing the PMML (i.e., the
jpmml).  I will fix it.

**Comment by ligadata-ahmad** [comment]
@ligadata-rich  I know where is the issue , I am testing it now . I will commit the changes in 15 min

**Comment by ligadata-rich** [comment]
Excellent.  Thanks.

**Comment by ligadata-ahmad** [comment]
Hi @ligadata-william  , I have tested adding and executing kpmml that we have in the samples using hashmap , everything worked fine. 
I am still facing issue when starting the engine using Hbase.

**Comment by ligadata-william** [comment]
This is ready to merge but there are conflicts and I'm unsure in a couple places which code is correct.

**Comment by ligadata-rich** [comment]
What command did you use to do the merge?  I can try it.  The
Sprint8FeaturesWithJpmml is pretty concentrated in the metadata,
metadataapi, and kamanja manager areas (the content and the integration of
the jpmml is there).


@ligadata-pokuri should also try this perhaps.  I think the most recent
merges to the Sprint8FeaturesWithJpmml were from him... so he would know
stuff that came in there.

**Comment by ligadata-william** [comment]
I checked out dev and ran:

git merge —no-ff Sprint8FeaturesWithJpmml

**Comment by ligadata-rich** [comment]
@ligadata-william,

I ran these steps with the shown results... and then tested... this seems
to work... There is a couple of minor conflicts...but simple ones.  I left
the function and the comment that wanted to replace the it in the
MetadataAPIImpl.  There are some formatting things... take the better ones
that line up with args (MetadataAPIImpl).  The build.sbt change uses the
factory of factory dep...

fwiw, I didn't use the -no-ff flag

rich@kobi:~/github/dev/devSpr8$ git clone -b dev
https://ligadata-rich@github.com/ligadata/kamanja.git
Cloning into 'kamanja'...
remote: Counting objects: 55417, done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 55417 (delta 51), reused 0 (delta 0), pack-reused 55228
Receiving objects: 100% (55417/55417), 81.34 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (23841/23841), done.
Checking connectivity... done.
rich@kobi:~/github/dev/devSpr8$ cd ka*/tr*
rich@kobi:~/github/dev/devSpr8/kamanja/trunk$ git branch
* dev
rich@kobi:~/github/dev/devSpr8/kamanja/trunk$ git checkout
Sprint8FeaturesWithJpmml
Branch Sprint8FeaturesWithJpmml set up to track remote branch
Sprint8FeaturesWithJpmml from origin.
Switched to a new branch 'Sprint8FeaturesWithJpmml'
rich@kobi:~/github/dev/devSpr8/kamanja/trunk$ git checkout dev
Switched to branch 'dev'
Your branch is up-to-date with 'origin/dev'.
rich@kobi:~/github/dev/devSpr8/kamanja/trunk$ git branch
  Sprint8FeaturesWithJpmml
* dev
rich@kobi:~/github/dev/devSpr8/kamanja/trunk$ git merge
Sprint8FeaturesWithJpmml
Auto-merging trunk/build.sbt
CONFLICT (content): Merge conflict in trunk/build.sbt
Auto-merging
trunk/Utils/Serialize/src/main/scala/com/ligadata/Serialize/JsonSerializer.scala
Removing trunk/Storage/SqlServer/src/test/resources/sqljdbc4-2.0.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/utilk-3.4.6.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/slf4j-simple-1.6.2.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/slf4j-api-1.7.6.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/postgresql-8.2-512.jdbc2ee.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/mt-services-0.2.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/log4j-1.2.15.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/joda-time-2.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/guava-16.0.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/flexjson-2.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/curfr-2.6.0.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/cuclient-2.6.0.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/commons-lang3-3.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/KamanjaWS-code/KAMANJAWS/WebContent/WEB-INF/lib/commons-configuration-1.7.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/zookeeper-3.4.6.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/zkclient-0.3.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/util-0.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/slf4j-log4j12-1.6.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/slf4j-api-1.7.6.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/scala-library-2.9.2.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/metrics-core-2.2.0.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/log4j-1.2.15.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/kafka_2.9.2-0.8.1.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/json-simple-1.1.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/guava-16.0.1.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/curator-recipes-2.6.0.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/curator-framework-2.6.0.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/curator-client-2.6.0.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/commons-logging-1.2.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/commons-lang-2.4.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/commons-configuration-1.7.jar
Removing
trunk/SampleApplication/MiddleWareAndUI/AlertsConsumer/lib/commons-collections-3.1.jar
Auto-merging
trunk/SampleApplication/EasyInstall/template/script/CreateQueues_Template.sh
Auto-merging
trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MetadataAPIImpl.scala
CONFLICT (content): Merge conflict in
trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/MetadataAPIImpl.scala
Auto-merging
trunk/MetadataAPI/src/main/scala/com/ligadata/MetadataAPI/ConceptUtils.scala
Auto-merging
trunk/Metadata/src/main/scala/com/ligadata/kamanja/metadata/mdmgr.scala
Auto-merging
trunk/Metadata/src/main/scala/com/ligadata/kamanja/metadata/mdelems.scala
Auto-merging
trunk/KamanjaManager/src/main/scala/com/ligadata/KamanjaManager/LearningEngine.scala
Auto-merging
trunk/KamanjaBase/src/main/scala/com/ligadata/KamanjaBase/ModelBase.scala
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/json-simple-1.1.1.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/jms-1.1.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/gcm-server.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/dhbcore.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.wmq.v6.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.wmq.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.wmq.factories.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.wmq.common.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.ref.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.provider.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.matchspace.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.jms.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.jms.internal.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.commonservices.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.msg.client.commonservices.j2se.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.mqjms.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.mq.jmqi.system.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.mq.jmqi.remote.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.mq.jmqi.local.jar
Removing
trunk/InputOutputAdapters/IbmMqSimpleInputOutputAdapters/lib/com.ibm.mq.jmqi.jar
Removing externals/odbc-jars/postgres.8.0.x/postgresql-8.0-325.jdbc3.jar
Removing externals/log4j/log4j-1.2.17.jar
Removing externals/kafka/kafka-jars/zookeeper-3.3.4.jar
Removing externals/kafka/kafka-jars/zkclient-0.3.jar
Removing externals/kafka/kafka-jars/slf4j-api-1.7.2.jar
Removing externals/kafka/kafka-jars/metrics-core-2.2.0.jar
Removing externals/kafka/kafka-jars/log4j-1.2.15.jar
Removing externals/kafka/kafka-jars/kafka_2.10-0.8.1.1.jar
Removing externals/joda/joda-time-2.3.jar
Removing externals/joda/joda-convert-1.5.jar
Removing
externals/datastax.cassandra/cassandra-driver-examples-stress-2.0.2.jar
Removing externals/datastax.cassandra/cassandra-driver-dse-2.0.2.jar
Removing externals/datastax.cassandra/cassandra-driver-core-2.0.2.jar
Removing externals/.DS_Store
Automatic merge failed; fix conflicts and then commit the result.
rich@kobi:~/github/dev/devSpr8/kamanja/trunk$ git branch
  Sprint8FeaturesWithJpmml
* dev
rich@kobi:~/github/dev/devSpr8/kamanja/trunk$
SampleApplication/EasyInstall/easyInstallKamanja.sh /tmp/drdigital
~/github/dev/devSpr8/kamanja/trunk ~/.ivy2 $KAFKA_HOME

**Pull request merged**
