### PR TITLE
open connection if null

### PR DESCRIPTION
**Pull request by ligadata-saleh**

### CODE REVIEW

**Comment by ligadata-pokuri** [comment]
@ligadata-william, can you review the code and test this?

**Comment by ligadata-william** [comment]
I'm testing this against branch 1.6.2-Berkley since the request is that these features be available on top of 1.6.2 now.

**Comment by ligadata-william** [comment]
This has been merged to 1.6.2-Berkley

**Comment by ligadata-saleh** [comment]
i can change the "createConsumerWithInputProperties" method that create the KafkaConsumer[String, String] to a singleton(design pattern) class  , that way only one instance will be created across all the project .

**Comment by ligadata-saleh** [comment]
@ligadata-william  i know you already marged this code , but i changed the code to create only one instance of the KafkaConsumer , am using lazy initialization right now please take a look and let me know if this is what you have in mind .

**Comment by ligadata-saleh** [comment]
reverting the code to the original state , no singlton needed

**Comment by ligadata-william** [comment]
This was merged into the 1.6.2-Berkley branch. Closing this pull request.

**Pull request closed without merging**
