### PR TITLE
Simplify api config

### PR DESCRIPTION
**Pull request by ligadata-ramana**
MetadataAPIConfig.properties requires only three properties. All the other properties optional

Example
#MetadataStore information
NodeId=1
MetadataDataStore={"StoreType": "h2db","connectionMode": "embedded","SchemaName": "kamanja","Location": "/media/home2/installKamanja151/Kamanja-1.5.1_2.11/storage","portnumber": "9100","user": "test","password": "test"}
ROOT_DIR=/media/home2/installKamanja151/Kamanja-1.5.1_2.11

All the other properties are optional and default to a value as defined today.

### CODE REVIEW

**Comment by ligadata-rich** [comment]
Ramana, when the python is merged into the main branch there will be some other options, then 

PYTHON_CONFIG={ "PYTHON_PATH": "{InstallDirectory}/python", "SERVER_BASE_PORT": 8100, "SERVER_PORT_LIMIT": 40, "SERVER_HOST": "localhost", "PYTHON_LOG_CONFIG_PATH": "{InstallDirectory}/python/bin/pythonlog4j.cfg", "PYTHON_LOG_PATH": "{InstallDirectory}/python/logs/pythonserver.log"}

will also be needed... iff there are python models to be used on the cluster.

**Comment by ligadata-william** [comment]
The CLASSPATH getting set isn't using the correct version of Kamanja. When I run an kamanja commands, I'm seeing the configuration get set to:
```
CLASSPATH => ExtDependencyLibs_2.11-1.5.1.jar:KamanjaInternalDeps_2.11-1.5.1.jar:ExtDependencyLibs2_2.11-1.5.1.jar
```
This needs to be updated to 1.6.0

**Comment by ligadata-william** [comment]
Additionally, contrary to Rich's earlier comment, Python configuration is now contained within cluster configuration. No need to account for it in MetadataAPIConfig.properties.

**Comment by ligadata-william** [comment]
Closing in favor of #1459

**Pull request closed without merging**
